### ISSUE TITLE
[Submission Pipeline] New Azure DevOps pipeline

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/test-infra#12679]
**Description**

To support `new-submission-workflow.yaml`, a new Azure pipeline needs to be implemented. This action should trigger only when `module-config.yaml` is modified within a version-based folder in a pull request.

**Acceptance Criteria**

- [x] Implement a new Azure pipeline configuration yaml (new file) that reacts exclusively to changes in version-based `module-config.yaml` files.
  - Ensure that `module-config.yaml` files located in channel-based folders do not trigger this pipeline.
  ```
  paths:
       include:
         - modules/*/module-config.yaml
      exclude:
         - modules/*/fast/module-config.yaml
         - modules/*/regular/module-config.yaml
         - modules/*/dev/module-config.yaml
         - modules/*/experimental/module-config.yaml
  ``` 
  - Reference `new-submission-workflow.yaml` in the `submission_process` stage.
- [x] Make sure the new Azure pipeline gets triggered based on this configuration.
- [x] No changes to the existing `azure-pipelines.yml`

**Attachments**

Existing Azure pipeline in the internal repo: `kyma/module-manifests/blob/main/azure-pipelines.yml`
