### ISSUE TITLE
[Submission Pipeline] Configure a new azure pipeline for the module-releases changes

### ISSUE THREAD

**Issue by nesmabadr** [kyma-project/test-infra#12961]
**Description**

With the changes introduced [here](https://github.com/kyma-project/lifecycle-manager/issues/2387), we only rely on the module name and the module-releases.yaml changes. So we need to create a new separate pipeline to handle the module -releases.yaml changes.

example of `module-releases.yaml`:
```
channels:
- channel: dev
  version: 1.32.0
- channel: experimental
  version: 1.34.0-experimental
- channel: regular
  version: 1.32.0
- channel: fast
  version: 1.34.0
```

**Reasons**

This pipeline does not need the other promotion pipeline steps. It only needs the module name and the changes to the module-releases.yaml file.

**Acceptance Criteria**

- [x] Configure a new azure pipeline for handling the module-releases
- [x] It should only get triggered when there is a change in the module-releases file (not module-config.yaml)
- [x] Remove the trigger of the new-azure-pipelines when there is a change in module-releases path (/kyma/module-manifests/blob/ed68691cc71c74eb4faf0d411abdafd689dc67a6/new-azure-pipelines.yml#L10 and /kyma/module-manifests/blob/ed68691cc71c74eb4faf0d411abdafd689dc67a6/new-azure-pipelines.yml#L26)
- [x] Add a new template for the steps required for this pipeline (Should just be removed from the new-submission-pipeline and placed in this template)

**Attachments**

![Image](https://github.com/user-attachments/assets/d8befdd8-e6c2-4568-af68-346c2c42908f)
