### ISSUE TITLE
[Submission Pipeline] Support setting module to `beta` and `internal`

### ISSUE THREAD

**Issue by c-pius** [kyma-project/test-infra#13152]
**Description**

Allow a module to be set to `beta` or `internal` in the new submission pipeline. The obvious candidate where to set these flags is the `module-releases.yaml` file (e.g. `kyma/module-manifests/blob/main/modules/telemetry/module-releases.yaml`). 

**Reasons**

Flags whether a module is `beta` or `internal` have been moved from ModuleTemplate level to ModuleReleaseMeta (whole module) level: https://github.com/kyma-project/lifecycle-manager/issues/2059

As we generate the ModuleReleaseMeta via the pipeline, we currently have no means for setting a module to `beta` or `internal`.

**Acceptance Criteria**

- [ ] Given `module-releases.yaml`:
  ```yaml
  internal: true
  beta: true
  # ...
  ```
- [ ] Then pipeline generates `module-release-meta.yaml` for all landscapes:
  ```yaml
  # ...
  spec:
    internal: true
    beta: true
    # ...
  ```

**Attachments**
