### ISSUE TITLE
Submission Pipeline: Ensure local files are supported

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/test-infra#13200]
**Description**

In order to [support restricted or air-gapped environments](https://github.com/kyma-project/modulectl/issues/237), the `modulectl` tool [supports local files](https://github.com/kyma-project/modulectl/pull/245) (as an alternative to public URLs) as a source for `manifest` and `defaultCR` data in the `create` command (module creation).

We need to be sure that the new submission pipeline also supports this mode of operation.

**Reasons**

As explained in https://github.com/kyma-project/modulectl/issues/237

**Acceptance Criteria**

Pipeline successfully submits a module version from a PR where local files are used for the 'manifest' and 'defaultCR' data - instead of `https://...` URLs.

An example `module-config.yaml` using local files - take a look at `manifest` and `defaultCR` attributes:

```
name: kyma-project.io/module/template-operator
version: 1.0.12
manifest: local-manifest.yaml
defaultCR: local-defaultcr.yaml
repository: https://github.com/kyma-project/template-operator
documentation: https://github.com/kyma-project/template-operator/blob/main/README.md
icons:
  - name: module-icon
    link: https://github.com/kyma-project/template-operator/blob/main/docs/assets/logo.png
```

_Note: The `modulectl` tool resolves the location of a file (`local-manifest.yaml` in the example above) relative to the `module-config.yaml` file location, i.e: the path used in the `--config-file` argument when invoking the `create` command._
