### ISSUE TITLE
Configure stubDomains for prow clusters

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/test-infra#1681]
Prow jobs like `pre-master-kyma-gke-integration`, `pre-master-kyma-gke-upgrade` spend very long time waiting for DNS propagation (~10min per job). We could decrease this delay by setting `stubDomains` value.

**Description**
In our build configuration we use the `build.kyma-project.io` domain. For every dynamically created cluster a subdomain is created. To verify if domain is accessible we use a dig command.
This is very slow cause we wait for a propagation to global DNS servers. According to [this](https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#effects-on-pods
) documentation we could pass dns resolution directly to servers responsible for this domain. 

Name servers for build.kyma-project.io:
- ns-cloud-d1.googledomains.com.
- ns-cloud-d2.googledomains.com.
- ns-cloud-d3.googledomains.com.
- ns-cloud-d4.googledomains.com.

We should set these servers in our build clusters configuration:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  stubDomains: |
    {"build.kyma-project.io": ["216.239.32.109", "216.239.34.109", "216.239.36.109", "216.239.38.109"]}
```

Important!
The dig command is executed on the workload cluster so we have to modify it and in the same time change provisioning scripts for gke. Otherwise there may be a situation when we confirmed that the domain is ready but our dynamically provisioned cluster can't access it because it does not have the same stubDomains configuration  

**Reasons**

Slashing ~10mins from jobs that take ~50mins is a 20% improvement :D

**Attachments**

This is how slow it is currently:
<img width="878" alt="Screen Shot 2019-10-29 at 14 35 37" src="https://user-images.githubusercontent.com/8530211/67772929-2fa7ba00-fa5b-11e9-9baa-7de32e1e3bcf.png">
