### ISSUE TITLE
Github connector is not working

### ISSUE THREAD

**Issue by kasiakepka** [kyma-project/test-infra#2063]
**Description**
Github connector is not working, users are not able to login to console via github account.

`dex-config` configmap is missing [following entry](https://github.com/kyma-project/test-infra/blob/e49cf0d4a20e829213fda087a62cc4e1965d3d4b/development/tools/cmd/enablegithubauth/main.go#L84):
```
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: %s
        clientSecret: %s
        redirectURI: %s
        orgs:
        - name: kyma-project
```

All integration clusters are affected.

**Expected result**

**Actual result**

**Steps to reproduce**

**Troubleshooting**
