### ISSUE TITLE
How to ensure build reproducibility in case of changes for test-infra

### ISSUE THREAD

**Issue by aszecowka** [kyma-project/test-infra#218]
In migration guide we advice using master branch for test-infra repository:
```
extra_refs:
        - org: kyma-project
          repo: test-infra
          base_ref: master
          path_alias: github.com/kyma-project/test-infra
```
But this can lead to non-reproducible builds when for example the `build.sh` file will be changed.

AC: 
- update the migration guide
- update all builds accordingly
- define a strategy for releases.
