### ISSUE TITLE
Proposal for caching external images in gcr

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/test-infra#2426]
**Description**

Kyma uses many 3rd party images from external docker registries that we have no control over and that are sometimes unreachable. 
List (may not be complete) of external images used by Kyma:
![Screenshot 2020-06-03 at 08 52 41](https://user-images.githubusercontent.com/8530211/83605095-9ce27700-a577-11ea-9811-03e9627576a6.png)

Please note that apart from images that are used directly there are also images that were used as base layer in our own components. When these base images are not available/broken **we can not build** our components.

In order to **mitigate security and reliability issues** we should copy them to our own registry. 
That also means that we have to change URLs in our charts.

**Implementation**

We should have a prow job that will copy images  based on a definition similar to this one:
```yaml
images:
- nameWithTag: "prometheus:v2.17.1"
  //sourceRepo:  "quay.io/prometheus/prometheus:v2.17.1" mistake
  sourceRepo:  "quay.io/prometheus/", 
  targetRepo:  "eu.gcr.io/kyma-project/external/prometheus/"

- nameWithTag: "grafana:7.0.1"
  sourceRepo:  "grafana/"
  targetRepo:  "eu.gcr.io/kyma-project/external/grafana/"
```

Please note that we can't just blindly copy from source to target because we can not guarantee that source image was not changed in the meantime.
For every image following steps need to be performed:
1. Pull source, check digest
1. Pull target, check digest
1. If target does not exist **copy the image**
1. If target exists compare the digests - if they are different we have an issue here - **job should fail**. This means that either someone by mistake changed it or we've chosen wrong tag that is not meant to be constant (i.e. "1.6" instead of "1.6.7")
1. If digest are the same there is nothing else to do

**Comment by mszostok** [comment]
Just a small suggestion to implementation, currently
```yaml
images:
- nameWithTag: "prometheus:v2.17.1",
  sourceRepo:  "quay.io/prometheus/prometheus:v2.17.1",
  targetRepo:  "eu.gcr.io/kyma-project/external/prometheus/",
```

so I see that here we have IMO duplication in `nameWithTag` and `sourceRepo`. Because this should be used for the mirroring only we should allow user to play with name and tag.  Also the `eu.gcr.io/kyma-project/external/` should be defined outside and the user should not be able to change it. Only the admin should decide where such mirror images should be pushed and we should require from user only info what kind of image he wants to push. Maybe such a layout will be better (separate fields to do not deal with parsing as you mentioned):

```yaml
images:
   - domainPrefix:  "prometheus"  # domain name to just have some images under one prefix (can be optional?)
       - source: 
         repo: "quay.io/prometheus",
         tag: "v2.17.1",
         name: "prometheus"
```

or even make a domain name as a key so no one will be able to do the duplication and we also enforce the nice grouping in YAML definition so it will more readable and by definition ensure the good use of that API
```yaml
images:
  prometheus:
     - source: 
        repo: "quay.io/prometheus",
        tag: "v2.17.1",
        name: "prometheus"
```

**Comment by adamwalach** [comment]
After some more discussion we came to a conclusion that we could simplify it even more:
```yaml
targetRepoPrefix:  "eu.gcr.io/kyma-project/external/"
images:
- source: "quay.io/prometheus/prometheus:v2.17.1"
- source: "grafana/grafana:7.0.1"
```
In this example target images would look like this:
```
eu.gcr.io/kyma-project/external/quay.io/prometheus/prometheus:v2.17.1
eu.gcr.io/kyma-project/external/grafana/grafana:7.0.1
```
