### ISSUE TITLE
[Proposal] Changes in chart definitions to be more registry-independent

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/test-infra#2453]
**Description**

Because of security reasons we need to use different registries for pre and post master artifacts. In order to improve local testing we could use a some kind of global-registry-prefix in Kyma.

Requirements:

- possibility of changing repo prefix
  Instead of
  `eu.gcr.io/kyma-project/develop/helm-controller:ced706ae`
  developer could use
  `my.local.repo/kyma-project/develop/helm-controller:ced706ae`

- images from master are pushed to a different repo than on PR, it means that we will have
  `eu.gcr.io/kyma-project/develop/helm-controller:ced706ae` on master, but
  `eu.gcr.io/kyma-project-dirty/develop/helm-controller:PR-123` on PR.
  We need a simple way of changing image URLs in chart definition at the same time.
  For example in [core/values.yaml](https://github.com/kyma-project/kyma/blob/master/resources/core/values.yaml#L11) there is: 

```
global:
   kymaOrgName: "kyma-project"
   containerRegistry:
     path: eu.gcr.io/kyma-project
  istio:
    gateway:
      name: kyma-gateway
  ui_acceptance_tests:
    version: b27021e2
  api_controller:
    dir:
    version: 3b88aaaf
   ```

 We need to be able to override `global.containerRegistry.path` value. That means there has to be a contract respected by all components.

**Acceptance Criteria**

**Attachments**
