### ISSUE TITLE
pjtester allow create prowjob with malformed syntax

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#2649]
**Description**

It's possible to crash plank by delivering malformed prowjob spec syntax to pjtester for test. PJtester should call checkconfig tool https://github.com/kubernetes/test-infra/tree/master/prow/cmd/checkconfig before scheduling prowjob to test on production prow cluster.

**Expected result**

PJtester is able to validate config and prowjobs if it conforms with spec and will not crash plank.

**Actual result**

Plank will crash when getting following prowjob spec.

**Steps to reproduce**

Example of malformed prowjob syntax where adding two more spaces to indent for lines starting from line "run_if_changed" is crashing plank.

```
- name: pre-master-demo
      branches:
        - ^master$
      decorate: true
      path_alias: github.com/kyma-project/kyma
      max_concurrency: 10
      spec:
        containers:
          - <<: *base_image_k16
            securityContext:
              privileged: true
            command:
              - "bash"
            env:
              - name: CLOUDSDK_COMPUTE_ZONE
                value: "europe-west4-b"
            args:
              - "-c"
              - "/home/prow/go/src/github.com/kyma-project/test-infra/prow/scripts/pjtester-demo.sh"
            resources:
              requests:
                memory: 200Mi
                cpu: 80m
# following lines are indented with two more spaces.
        # following regexp won't start build if only Markdown files were changed
        run_if_changed: "^((resources\\S+|installation\\S+|tools/kyma-installer\\S+)(\\.[^.][^.][^.]+$|\\.[^.][^dD]$|\\.[^mM][^.]$|\\.[^.]$|/[^.]+$))"
        labels:
          preset-build-pr: "true"
          <<: *gke_job_labels_template
        extra_refs:
          - <<: *test_infra_ref
            base_ref: master
```

See #2289
