### ISSUE TITLE
Clusters kyma-gke-nightly, kyma-gke-weekly and kyma-aks-nightly failing to provision.

### ISSUE THREAD

**Issue by Ressetkk** [kyma-project/test-infra#2792]
**Description**
The `kyma-gke-nightly` and `kyma-aks-nightly` fail to provision due to connection error in `istio-proxy` container from `tracing-kcproxy` pod. Basically CrashLoopBackoff prevents the installation to finish.

There are a lot of errors in the `kcproxy` container:
```
{"level":"info","ts":1601034768.864551,"msg":"attempting to retrieve configuration discovery url","url":"https://dex.nightly.a.build.kyma-project.io","timeout":"30s"}
{"level":"warn","ts":1601034769.8688877,"msg":"failed to get provider configuration from discovery","error":"Get \"https://dex.nightly.a.build.kyma-project.io/.well-known/openid-configuration\": read tcp 10.220.0.28:45414->34.91.56.30:443: read: connection reset by peer"}
```
I've checked the DNS resolution by manually removing the DNS record from nightly cluster but after the retriggering the job the problem still occurs. That assumes infra-related problem should not be the case here.

The sidecar container `istio-proxy` also has a lot issues regarding not working connections:
```
[Envoy (Epoch 0)] [2020-09-25 08:22:39.361][22][warning][config] [external/envoy/source/server/listener_impl.cc:196] Listener connection limit runtime key envoy.resource_limits.listener.0.0.0.0_5000.connection_limit is empty. There are currently no limitations on the number of accepted connections for listener 0.0.0.0_5000.
[Envoy (Epoch 0)] [2020-09-25 08:22:39.363][22][warning][config] [external/envoy/source/server/listener_impl.cc:196] Listener connection limit runtime key envoy.resource_limits.listener.10.223.253.220_14269.connection_limit is empty. There are currently no limitations on the number of accepted connections for listener 10.223.253.220_14269.
[Envoy (Epoch 0)] [2020-09-25 08:22:39.365][22][warning][config] [external/envoy/source/server/listener_impl.cc:196] Listener connection limit runtime key envoy.resource_limits.listener.10.223.241.213_15029.connection_limit is empty. There are currently no limitations on the number of accepted connections for listener 10.223.241.213_15029.

---

2020-09-25T08:26:04.484839Z	error	Request to probe app failed: Get http://localhost:10001/oauth/health: dial tcp 127.0.0.1:10001: connect: connection refused, original URL path = /app-health/kcproxy/livez
app URL path = /oauth/health
```

logs from Kubectl:
```
kgp -n kyma-system tracing-kcproxy-5fdd59f475-4q7n6
NAME                               READY   STATUS             RESTARTS   AGE
tracing-kcproxy-5fdd59f475-4q7n6   1/2     CrashLoopBackOff   45         126m
```
```
kdp -n kyma-system tracing-kcproxy-5fdd59f475-4q7n6 
Events:
  Type     Reason     Age                   From                                             Message
  ----     ------     ----                  ----                                             -------
  Warning  Unhealthy  11m (x127 over 126m)  kubelet, gke-nightly-default-pool-b4c6230a-r78b  Liveness probe failed: HTTP probe failed with statuscode: 500
  Warning  BackOff    95s (x500 over 124m)  kubelet, gke-nightly-default-pool-b4c6230a-r78b  Back-off restarting failed container
```
The problem started occurring since today's morning.

**Expected result**
The clusters are up and running.

**Actual result**
Clusters cannot be provisioned.

**Steps to reproduce**
Rerun `kyma-gke-nightly` or `kyma-aks-nightly` job on Prow.

**Troubleshooting**
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-gke-nightly/1309342160394391553
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-gke-nightly/1309402308055928832
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-gke-nightly/1309427726444138497
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-gke-nightly/1309453520218361856

**Comment by Tomasz-Smelcerz-SAP** [comment]
@Ressetkk 
I've checked the nightly cluster.
The main LoadBalancer that handles almost entire traffic to the cluster (istio-ingressgateway) has IP: `34.90.248.252`
But DNS resolves `*.nightly.a.build.kyma-project.io` to a different address:
```
host "dex.nightly.a.build.kyma-project.io"
dex.nightly.a.build.kyma-project.io has address 34.91.56.30

You can verify that dex responds correctly by adding proper addres into your hosts file to override invalid DNS resolution.

**Comment by Ressetkk** [comment]
So after putting some work on tracing the issue I've traced the root cause of the problem with help from @Demonsthere (thanks!). We were able to address the thing that broke cluster provisioning. The latest changes in the [installer-config-production.yaml.tpl](https://github.com/kyma-project/kyma/blob/master/installation/resources/installer-config-production.yaml.tpl) introduced a new way of configuration for istio-ingressgateway. In provisioning scripts we were using the following override to provide proper IP for istio:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: "istio-overrides"
  namespace: "kyma-installer"
  labels:
    installer: overrides
    kyma-project.io/installation: ""
    component: istio
data:
  gateways.istio-ingressgateway.loadBalancerIP: "${GATEWAY_IP_ADDRESS}"
```
When a new configuration syntax is used this override will not be respected so that leads for istio to issue random IP address instead of pre-generated one.

`kyma install` in the scripts affected scripts (kyma-aks-long-lasting.yaml, kyma-gke-long-lasting.yaml) uses multiple `-o` flags to define override yamls. As far as I know there is no way to merge two YAML files using this flag. To be precise, let's define two files:
override1.yaml
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-overrides
  namespace: kyma-installer
  labels:
    installer: overrides
    component: istio
    kyma-project.io/installation: ""
data:
  kyma_istio_operator: |-
    apiVersion: install.istio.io/v1alpha1
    kind: IstioOperator
    metadata:
      namespace: istio-system
    spec:
      components:
        ingressGateways:
        - name: istio-ingressgateway
          k8s:
            hpaSpec:
              maxReplicas: 10
              minReplicas: 3
      values:
        global:
          proxy:
            resources:
              requests:
                cpu: 150m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 1024Mi
```

override2.yaml
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-overrides
  namespace: kyma-installer
  labels:
    installer: overrides
    component: istio
    kyma-project.io/installation: ""
data:
  kyma_istio_operator: |-
    apiVersion: install.istio.io/v1alpha1
    kind: IstioOperator
    spec:
      components:
        ingressGateways:
          - name: istio-ingressgateway
            k8s:
              service:
                loadBalancerIP: 1.2.3.4
                type: LoadBalancer
```

when used `kyma install -o=override1.yaml -o=override2.yaml` the installer will use a merged override which looks like this:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-overrides
  namespace: kyma-installer
  labels:
    installer: overrides
    component: istio
    kyma-project.io/installation: ""
data:
  kyma_istio_operator: |-
    apiVersion: install.istio.io/v1alpha1
    kind: IstioOperator
    metadata:
      namespace: istio-system
    spec:
      components:
        ingressGateways:
        - name: istio-ingressgateway
          k8s:
            service:
              loadBalancerIP: 1.2.3.4
              type: LoadBalancer
            hpaSpec:
              maxReplicas: 10
              minReplicas: 3
      values:
        global:
          proxy:
            resources:
              requests:
                cpu: 150m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 1024Mi
```
As I understand currently it's not possible to do it. I've created a PR with workaround which edits the installer-config-production.yaml.tpl on-the-fly using yq.
