### ISSUE TITLE
Branch Protector sets optional job as required

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/test-infra#303]
**Description**

Branch Protector sets `test-infra-governance` and `website-governance` as required, but they are not defined as required in configuration:
```
branch-protection:
  orgs:
    kyma-project:
      repos:
        test-infra:
          #TODO: move to default config for organization
          enforce_admins: false
          required_pull_request_reviews:
            dismiss_stale_reviews: false
            require_code_owner_reviews: true
            required_approving_review_count: 1
          protect: true
          #TODO: end move
          required_status_checks:
            contexts:
              - license/cla #TODO: move to default config for organization
              - test-infra-bootstrap
              - test-infra-bootstrap-helm
              - test-infra-buildpack-golang
              - test-infra-buildpack-node
              - test-infra-buildpack-node-chromium
              - test-infra-cleaner
              - test-infra-development-tools
              - test-infra-test-jobs-yaml-definitions
              - test-infra-validate-scripts
              - test-infra-validate-configs
        website:
          #TODO: move to default config for organization
          enforce_admins: false
          required_pull_request_reviews:
            dismiss_stale_reviews: false
            require_code_owner_reviews: true
            required_approving_review_count: 1
          #TODO: end move
          branches:
            master:
              protect: true
          required_status_checks:
            contexts:
              - license/cla #TODO: move to default config for organization
              - website
              - website-tools-documentation-generator
              - continuous-integration/jenkins/pr-head #TODO: replace by governance job
```

**Expected result**

Only jobs defined as required should block PR.

**Actual result**

All jobs that send status to GitHub are defined as required

**Steps to reproduce**

Enable Branch Protector (it is suspended right now) and observe logs:
```
{"client":"github","component":"branchprotector","level":"info","msg":"Throttle(300, 100)","time":"2018-12-07T14:30:02Z"}
{"client":"github","component":"branchprotector","level":"info","msg":"GetBranches(kyma-project, test-infra)","time":"2018-12-07T14:30:02Z"}
{"client":"github","component":"branchprotector","level":"info","msg":"GetBranches(kyma-project, test-infra)","time":"2018-12-07T14:30:03Z"}
{"client":"github","component":"branchprotector","level":"info","msg":"GetBranches(kyma-project, website)","time":"2018-12-07T14:30:03Z"}
{"client":"github","component":"branchprotector","level":"info","msg":"UpdateBranchProtection(kyma-project, test-infra, master, {\"required_status_checks\":{\"strict\":false,\"contexts\":[\"license/cla\",\"test-infra-bootstrap\",\"test-infra-bootstrap-helm\",\"test-infra-buildpack-golang\",\"test-infra-buildpack-node\",\"test-infra-buildpack-node-chromium\",\"test-infra-cleaner\",\"test-infra-development-tools\",\"test-infra-governance\",\"test-infra-test-jobs-yaml-definitions\",\"test-infra-validate-configs\",\"test-infra-validate-scripts\"]},\"enforce_admins\":null,\"required_pull_request_reviews\":{\"dismissal_restrictions\":{},\"dismiss_stale_reviews\":false,\"require_code_owner_reviews\":true,\"required_approving_review_count\":1},\"restrictions\":null})","time":"2018-12-07T14:30:03Z"}
{"client":"github","component":"branchprotector","level":"info","msg":"GetBranches(kyma-project, website)","time":"2018-12-07T14:30:03Z"}
{"client":"github","component":"branchprotector","level":"info","msg":"UpdateBranchProtection(kyma-project, website, master, {\"required_status_checks\":{\"strict\":false,\"contexts\":[\"continuous-integration/jenkins/pr-head\",\"license/cla\",\"website\",\"website-governance\",\"website-tools-documentation-generator\"]},\"enforce_admins\":null,\"required_pull_request_reviews\":{\"dismissal_restrictions\":{},\"dismiss_stale_reviews\":false,\"require_code_owner_reviews\":true,\"required_approving_review_count\":1},\"restrictions\":null})","time":"2018-12-07T14:30:05Z"}
```

**Troubleshooting**
