### ISSUE TITLE
Improve the release process - github action

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/test-infra#3174]
**Description**

In order to make the release process easier and more secure we should change the current trigger for creating GitHub release. Currently, it is triggered by creating a tag, this has following consequences:
- it is easy to misspell the git command and push the wrong tag name
- there is no approval process - we can't limit who can create a release

The solution is to create a github action that can be triggered only manually. By adding a separate environment to the definition we can introduce a group of approvers that need to confirm the execution process.

Example:
```yaml
# This is a basic workflow to help you get started with Actions

name: manual_test

on:
  # Trigger workflow manually
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # The environment is defined separately and contans list of approvers
    environment: release-env
    # Dummy steps
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

```
