### ISSUE TITLE
Investigate how to provide sourcecode for jobs

### ISSUE THREAD

**Issue by aszecowka** [kyma-project/test-infra#37]
Presubmit jobs can be "decorated" (see UtilityConfig in prow repo), and following options can be specified:
```
	// PathAlias is the location under <root-dir>/src
	// where the repository under test is cloned. If this
	// is not set, <root-dir>/src/github.com/org/repo will
	// be used as the default.
	PathAlias string `json:"path_alias,omitempty"`
	// CloneURI is the URI that is used to clone the
	// repository. If unset, will default to
	// `https://github.com/org/repo.git`.
	CloneURI string `json:"clone_uri,omitempty"`
	// SkipSubmodules determines if submodules should be
	// cloned when the job is run. Defaults to true.
	SkipSubmodules bool `json:"skip_submodules,omitempty"`
```

On the other hand, it seems that istio is not always using this functionality (https://github.com/istio/test-infra/blob/master/prow/cluster/jobs/istio/proxy/istio.proxy.master.yaml), where they specify as a argument to the container path to the repository:
```
bazel_spec: &bazel_spec
  containers:
  - image: gcr.io/istio-testing/prowbazel:0.4.13
    args:
    - "--repo=github.com/$(REPO_OWNER)/$(REPO_NAME)=$(PULL_REFS)"
    - "--clean"
    - "--timeout=60"
    # Bazel needs privileged mode in order to sandbox builds.
    securityContext:
      privileged: true
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "24Gi"
        cpu: "7000m"
  nodeSelector:
    testing: build-pool
```

Keep in mind that for component jobs, probably we should not clone whole repository and use sparse checkout and maybe shallow clone.

AC:
- Prow job that checkout sourcecode for one component
