### ISSUE TITLE
Add image version to image-syncer

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/test-infra#3861]
**Description**

[Image syncer](https://github.com/kyma-project/test-infra/tree/main/development/image-syncer) needs to support a scenario where the source image changes, but the tag stays the same. We encountered situation like that several times, most frequenly in postgres and busybox images.
In order to maintain immutable images in our registry, we should introduce some kind of suffix that is added to the original name.

**Proposal**
Let's add an optional field "version" (type integer) that can be used to override target tag. When this field is set, `image-syncer` should append `-v{version}` to the source tag.

***Example***
Definition:
```
targetRepoPrefix:  "eu.gcr.io/kyma-project/external/"
images:
- source: "alpine:3.13.5"
- source: "bitnami/keycloak-gatekeeper:10.0.0"
  version: 1
- source: "bitnami/postgres-exporter:0.8.0-debian-10-r28"
- source: "busybox:1.32.0"
  version: 3
- source: "curlimages/curl:7.70.0"
```

Result for busybox: `eu.gcr.io/kyma-project/external/busybox:1.32.0-v3`
