### ISSUE TITLE
Add ability to sign synced image using cosign to image-syncer.

### ISSUE THREAD

**Issue by Ressetkk** [kyma-project/test-infra#3975]
**Description**
It's needed to have all synced images using image-synced to be securely signed using the crypto key.
It has to be implemented in the image-syncer code to optionally sign the images using global and/or local override for each image that is meant to be cloned. Example config:
```yaml
targetRepoPrefix: xxx
sign: true
images:
-  source: alpine:signed
-  source: alpine:unsigned
   sign: false
```

**Reasons**
All images used by kyma components have to be confirmed and signed in order to have them working.

**Acceptance Criteria**
Images are signed after push

**Attachments**
