### ISSUE TITLE
Job kyma-gke-nigthly fails

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/test-infra#4229]
**Description**

The job fails because of unsupported flag in kyma cli:
```
Error: unknown flag: --timeout
```

Additionally, job seems to be outdated as it deals with the components that are not part of Kyma 2.0 release (dex, apiserver proxy).

**Comment by pbochynski** [comment]
PR with fix: https://github.com/kyma-project/test-infra/pull/4226

**Comment by pbochynski** [comment]
Another finding. With the new installation method (kyma deploy) the installer overrides do not work. The following istio configuration should be passed to the kyma cli directly:
```
    apiVersion: install.istio.io/v1alpha1
    kind: IstioOperator
    metadata:
      namespace: istio-system
    spec:
      components:
        ingressGateways:
          - name: istio-ingressgateway
            k8s:
              service:
                loadBalancerIP: ${GATEWAY_IP_ADDRESS}
                type: LoadBalancer
```
https://github.com/kyma-project/test-infra/blob/51620ea5d2b229162b1072557bfae15cb8b39178/prow/scripts/resources/kyma-installer-overrides.tpl.yaml#L36-L47
