### ISSUE TITLE
Improve Prow cluster autoscaling

### ISSUE THREAD

**Issue by aszecowka** [kyma-project/test-infra#467]
Currently, k8s node pools have enabled autoscaling with the following configuration:
- min size: 2
- max size 10

But we observed, that during weekends, when only period jobs are executed, the cluster has 3 nodes.
Also during the working day, the cluster has 5 nodes when utilization of all nodes was below 25%

We need to investigate, if we can optimize resource usage.

**Comment by joek** [comment]
There are different measurement which are influencing the autoscaler. As a first guess, I would assume something is blocking one note from shuting down at the weekend (see https://cloud.google.com/kubernetes-engine/docs/concepts/cluster-autoscaler?hl=en#considering_pod_scheduling_and_disruption). 

During the day, there might be other problems, which I will have a look into as soon as I have access to the gcp account.

**Comment by joek** [comment]
There are two things which are strange:
1. During the weekend CPU and Memory usage is going down. Nevertheless the system was staying at 5 Nodes. We have to check what's happen there. Probably some pods are blocking the turn off.
2. CPU and Memory Request metric is not going down at night. It seems, the completed pods are still requesting the resources without using them.

Actions:
1. Force kill all completed nodes to check if this will bring the request metrics down.
2. Check if this has an impact on the autoscaler and which pods are still around blocking the shutdown.

**Comment by joek** [comment]
After removing all completed tasks, the requested memory was decreased dramatically.

![Screen Shot 2019-01-17 at 17.49.22.png](https://images.zenhubusercontent.com/5b7eaa8008da7624d8ea983f/943464ee-3adf-442c-82e7-d7b777c06b54)

The following jobs where still running:
```gke-kyma-prow-default-pool-7c62e362-f9mh   cert-manager-7f9fb4c8bc-b8c75
gke-kyma-prow-default-pool-7c62e362-f9mh   deck-7d49bd857c-pg8x6
gke-kyma-prow-default-pool-7c62e362-f9mh   fluentd-gcp-v3.1.0-fgjvx
gke-kyma-prow-default-pool-7c62e362-f9mh   hook-6786bf8886-nwr92
gke-kyma-prow-default-pool-7c62e362-f9mh   horologium-5879bb5c49-6rwzk
gke-kyma-prow-default-pool-7c62e362-f9mh   kube-proxy-gke-kyma-prow-default-pool-7c62e362-f9mh
gke-kyma-prow-default-pool-7c62e362-f9mh   metrics-server-v0.2.1-fd596d746-2ltjg
gke-kyma-prow-default-pool-7c62e362-f9mh   monitoring-prometheus-node-exporter-drg8r
gke-kyma-prow-default-pool-7c62e362-f9mh   prometheus-monitoring-prometheus-oper-prometheus-0
gke-kyma-prow-default-pool-7c62e362-f9mh   pushgateway-69bdfc869-cxzbv
gke-kyma-prow-default-pool-7c62e362-f9mh   sinker-7ffc79558-wbqdw
gke-kyma-prow-default-pool-7c62e362-f9mh   tide-69c4bc76d9-wqsk2
gke-kyma-prow-default-pool-7c62e362-j0c2   alertmanager-monitoring-prometheus-oper-alertmanager-0
gke-kyma-prow-default-pool-7c62e362-j0c2   deck-7d49bd857c-x8z89
gke-kyma-prow-default-pool-7c62e362-j0c2   event-exporter-v0.2.3-85644fcdf-lhf8w
gke-kyma-prow-default-pool-7c62e362-j0c2   fluentd-gcp-v3.1.0-hsnbv
gke-kyma-prow-default-pool-7c62e362-j0c2   hook-6786bf8886-kgc5x
gke-kyma-prow-default-pool-7c62e362-j0c2   kube-dns-548976df6c-hqqrb
gke-kyma-prow-default-pool-7c62e362-j0c2   kube-dns-autoscaler-67c97c87fb-dfkg2
gke-kyma-prow-default-pool-7c62e362-j0c2   kube-proxy-gke-kyma-prow-default-pool-7c62e362-j0c2
gke-kyma-prow-default-pool-7c62e362-j0c2   monitoring-prometheus-node-exporter-h6xxd
gke-kyma-prow-default-pool-7c62e362-j0c2   nginx-ingress-controller-87554c57b-r6qn8
gke-kyma-prow-default-pool-7c62e362-nn5c   01214de0-1a71-11e9-9b61-0a580a2c0008
gke-kyma-prow-default-pool-7c62e362-nn5c   9969c9b8-1a76-11e9-b40a-0a580a2c0103
gke-kyma-prow-default-pool-7c62e362-nn5c   f368e502-1a73-11e9-b40a-0a580a2c0103
gke-kyma-prow-default-pool-7c62e362-nn5c   fluentd-gcp-v3.1.0-4kh6n
gke-kyma-prow-default-pool-7c62e362-nn5c   kube-proxy-gke-kyma-prow-default-pool-7c62e362-nn5c
gke-kyma-prow-default-pool-7c62e362-nn5c   l7-default-backend-5bc54cfb57-r6p5v
gke-kyma-prow-default-pool-7c62e362-nn5c   monitoring-kube-state-metrics-6bd59ffc4d-lgg6h
gke-kyma-prow-default-pool-7c62e362-nn5c   monitoring-prometheus-node-exporter-cbhr7
gke-kyma-prow-default-pool-7c62e362-nn5c   monitoring-prometheus-oper-operator-b84fb4864-gt4qw
gke-kyma-prow-default-pool-7c62e362-nn5c   plank-854bdfbfc8-s62nl
gke-kyma-prow-default-pool-7c62e362-nnqf   19862aaf-1a77-11e9-910f-0a580a2c0007
gke-kyma-prow-default-pool-7c62e362-nnqf   fluentd-gcp-scaler-697b966945-6c9ll
gke-kyma-prow-default-pool-7c62e362-nnqf   fluentd-gcp-v3.1.0-czsg4
gke-kyma-prow-default-pool-7c62e362-nnqf   heapster-v1.6.0-beta.1-8d8fd5759-d62bn
gke-kyma-prow-default-pool-7c62e362-nnqf   kube-dns-548976df6c-6fxb5
gke-kyma-prow-default-pool-7c62e362-nnqf   kube-proxy-gke-kyma-prow-default-pool-7c62e362-nnqf
gke-kyma-prow-default-pool-7c62e362-nnqf   monitoring-prometheus-node-exporter-hmqjc
gke-kyma-prow-default-pool-7c62e362-t36n   1984a3c8-1a77-11e9-910f-0a580a2c0007
gke-kyma-prow-default-pool-7c62e362-t36n   f3684421-1a73-11e9-b40a-0a580a2c0103
gke-kyma-prow-default-pool-7c62e362-t36n   fluentd-gcp-v3.1.0-2kxll
gke-kyma-prow-default-pool-7c62e362-t36n   kube-proxy-gke-kyma-prow-default-pool-7c62e362-t36n
gke-kyma-prow-default-pool-7c62e362-t36n   monitoring-grafana-64dd66fddb-llxlj
gke-kyma-prow-default-pool-7c62e362-t36n   monitoring-prometheus-node-exporter-gt4ft
gke-kyma-prow-default-pool-7c62e362-t36n   tiller-deploy-5478dfbcbf-sdb7w```

Next step:
- Figure out what happens to the left over pods if there is a pod preventing downscale of nodes.

**Comment by joek** [comment]
Added a ```poddisruptionbudget``` to most pods inside the kube-system namespace. Let's take the weekend to figure out if this is bringing back the scaling.

```
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: k8s-event-exporter
  namespace: kube-system
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
        k8s-app: event-exporter
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: k8s-fluentd-gcp-scaler
  namespace: kube-system
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
        k8s-app: fluentd-gcp-scaler
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: k8s-kube-dns-autoscaler
  namespace: kube-system
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
        k8s-app: kube-dns-autoscaler
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: k8s-glbc
  namespace: kube-system
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
        k8s-app: glbc
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: k8s-metrics-server
  namespace: kube-system
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
        k8s-app: metrics-server
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: app-helm
  namespace: kube-system
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
        app: helm
```
