### ISSUE TITLE
[CI] Define required-matching-labels for kyma-project repositories

### ISSUE THREAD

**Issue by Ressetkk** [kyma-project/test-infra#4968]
To enforce some rules about defining manual labels on issues, like `area/` or `kind/`, we should enable `require-matching-label` plugin that will add label `needs-kind, needs-area` etc. and Write a comment that defining such label is required.

From plugin description:
>The require-matching-label plugin is a configurable plugin that applies a label to issues and/or PRs that do not have any labels matching a regular expression. An example of this is applying a 'needs-sig' label to all issues that do not have a 'sig/*' label. This plugin can have multiple configurations to provide this kind of behavior for multiple different label sets. The configuration allows issue type, PR branch, and an optional explanation comment to be specified.
```yaml
require_matching_label:
  - # Branch is the branch ref of PRs that this config applies to.
    # This field is only valid if `prs: true` and may be omitted to apply this
    # config across all branches in the repo or org.
    branch: master

    # GracePeriod is the amount of time to wait before processing newly opened
    # or reopened issues and PRs. This delay allows other automation to apply
    # labels before we look for matching labels.
    # Defaults to '5s'.
    grace_period: 5s

    # Issues is a bool indicating if this config applies to issues.
    issues: true

    # MissingComment is the comment to post when we add the MissingLabel to an
    # issue. This is typically used to explain why MissingLabel was added and
    # how to move forward.
    # This field is optional. If unspecified, no comment is created when labeling.
    missing_comment: Please add a label referencing the kind.

    # MissingLabel is the label to apply if an issue does not have any label
    # matching the Regexp.
    missing_label: needs-kind

    # Org is the GitHub organization that this config applies to.
    org: org

    # PRs is a bool indicating if this config applies to PRs.
    prs: true

    # Regexp is the string specifying the regular expression used to look for
    # matching labels.
    regexp: ^kind/

    # Repo is the GitHub repository within Org that this config applies to.
    # This fields may be omitted to apply this config across all repos in Org.
    repo: repo
```
