### ISSUE TITLE
Secret obscurity in Prow logs

### ISSUE THREAD

**Issue by Ressetkk** [kyma-project/test-infra#5250]
We should investigate how to achieve secret obscurity in logs for ProwJob. For now there is no secret obscurity and anyone can just print out the secret value that is in cluster, potentially leaking the secret value to the world.

Some kind of obscurity needs to be achieved when we show the logs in the deck and export it to the file when the job is finished.
This requirement is for security hardening and preventing potential leakages of secrets.

Once we have something in place this issue should be transferred to the kubernetes/test-infra, since this issue tackles Prow functionality directly.

/kind feature
/area prow
/area security

**Comment by Ressetkk** [comment]
Actually [sidecar image has functionality to censor the secrets](https://github.com/kubernetes/test-infra/blob/master/prow/pod-utilities.md#automatic-censoring-of-secret-data). It's a matter of one change in the decoration config to enable it on-demand. We can add it only to the jobs that use secrets, or enable it globally. Not it will slow down the ProwJob execution a bit.

**Comment by Ressetkk** [comment]
For the demo purposes I created secret `super-secret` on untrusted cluster with value `super-secret-value`. I also created ProwJob that uses the decoration config with enabled censoring.
```
periodics:
  - name: demo-secret-obscurity
    annotations:
      testgrid-create-test-group: "false"
    cron: "0 0 0 * * *"
    skip_report: true
    decorate: true
    cluster: untrusted-workload
    spec:
      containers:
        - image: "eu.gcr.io/kyma-project/test-infra/kyma-integration:v20220524-0196d249"
          command:
            - "bash"
          args: ["-c", "ls -lah /var/secret && cat /var/secret/secret"]
          volumeMounts:
            - name: super-secret
              mountPath: /var/secret
              readOnly: true
      volumes:
        - name: super-secret
          secret:
            secretName: super-secret
```

For the execution you can see the logs [here](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/demo-secret-obscurity/1534145829512679424). It shows that the directory /var/secret/secret exists and when I try to `cat` the mounted secret file it obscures it with `XXXXX`.
