### ISSUE TITLE
Enable pjtester to change prowjob definition based on pjtester configuration file.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#5991]
**Description**

Present, pjtester loads prowjob definition from file stored in github.com or provided within a pull request. Prowjobs names to load are provided in pjtester configuration file in pull request. It might be useful to extend possibility to change prowjob definition directly from pjtester configuration file. Currently it's possible to define pull request number to use as prowjob refs and switch prowjob reporting to slack. With upcoming changes, which will allow to start pjtester from any repository it will be convenient to change prowjob definition without need for separate pull request in repository where prowjob definition is stored. This feature should target scenario where changes in prowjob definition are small like environment variables, image name and tag. Values provided in pjtester config file will be added to the prowjob definition and will override existing values load from prowjob definition file.

Example pjtester.yaml file.
```
pjConfigs:
  kyma-project:
    test-infra:
      - pjName: pre-test-infra-validate-dockerfiles
        envs:
          - env1_name: env1_value
          - env2_name: env2_value
         image: image_url:image_tag
```

**Acceptance Criteria**

- [ ] pjtester allow changing prowjob environment variables based on pjtester.yaml file
- [ ] pjtester allow changing prowjob image based on pjtester.yaml file
