### ISSUE TITLE
[CI] image-builder: customized builds of multiple images in one job

### ISSUE THREAD

**Issue by Ressetkk** [kyma-project/test-infra#6062]
/kind feature
/area ci

This feature came up into my mind as I looked at Kyma components. One of the components, function-runtimes, contains Dockerfiles that are built in single makefile step. With current approach kaniko-build can't guarantee that all images will be built using single job. You have to have each runtime defined as separate job. This seems very inconvenient. 

So, in my opinion image-builder should allow defining which images to build from Directory. The impact is that we could define less jobs when one project needs to build more images than one. Previous functionality of building one Dockerfile cannot be broken.

With that said, I suggest that adding another flag `--builds` that will contain path to the file `builds.yaml` relative to `--context` flag. That flag would be mutually exclusive with `--dockerfile` and proper information should be shown to user if both flag are used.

The contents of the `builds.yaml` can look the same as current flags we provide to the tool:
```yaml
builds:
- name: build
  context: subdirectory # path of a sub-image relative to program's '--context' flag
  dockerfile: Dockerfile # path to Dockerfile under 'context'. Can be a subdirectory
  directory: subdir # subdirectory of the image in registry
  tags:
  - tag2
  - tag3
  ```
  
  variants would work the same way as in single build where variants.yaml file is placed along with the Dockerfile to build them.
