### ISSUE TITLE
Dedicated field for periodics i pjtester.yaml

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#6352]
**Description**

Periodic prowjobs are not defined for repositories. If periodic prowjob needs to clone repository it must be defined in extra refs section. At present pjtester.yaml file syntax require to provide an org and repo names for which a prowjob is defined. It's not possible to meet this requirement for periodics. As a workaround when testing periodic, a developer must provide kyma-project/test-infra. `pjtester.yaml` syntax should support a logic way defining periodics tests which doesn't require providing org, repo names.

Example:

```
pjConfigs:
  prowJobs:
    periodics:
    - pjName: "periodic-name-01"
    - pjName: "periodic-name-02"
      report: true
    kyma-project:
      kyma:
      - pjName: "presubmit-test-job"
        report: true
      - pjName: "orphaned-disks-cleaner"
```

**Reasons**

To test periodic prowjob a developer must use workaround which is against a logic a developer would expect.

**Acceptance Criteria**

A `pjtester.yaml` file doesn't require providing org and repo names for periodics tests.
