### ISSUE TITLE
[CI Refurbishment] Verify integration of AzureDevops as quality gate for Github.com PRs

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/test-infra#6583]
**Description**

We have to verify that the integration of an SAP Azure DevopsPipeline as quality gate for a Github.com works.

Expected is to implement a simple AzruDevopsOps pipeline and configure it to become a quality gate for a PR of an public Github.com repository.

* Create two simple Azure Devops Pipeline (one which is always failing and another one which is finishing successfully).
* Create a public Github.com repository
* Configure these two pipelines as quality gate for PRs to this repository (by using Webhooks etc.).
* Open a PR to the repository 

AC:
- [x] We have a working integration between a Githbu.com repository and SAP AzureDevops
- [x] An example setup (using Githhub.com + SAP AzureDevops)  which confirmed that SAP AzureDevops can act as quality gate for PRs to a public repository in Github.com

**Comment by tobiscr** [comment]
Depends on #6585 + #6621

**Comment by KacperMalachowski** [comment]
We have access from Azure to GitHub and from GitHub to Azure.

And that concludes good news. The bad one are:
 - There is no way to properly filter which event trigger webhook call in GitHub.
 - There is no way to trigger pipeline on more than one GitHub event (e.g. reopened and synchronize for PR's)

Syntax for webhook with filters definition is:
```yaml
resources:
  webhooks:
    - webhook: <webhook name>
      connection: <connection name>
      filters:
        - path: <JSONPath>
           value: <path value>
```

Problem is all filters are AND condition so all of them have to exist with proper value. That behavior prevents us from using this syntax:

```yaml
resources:
  webhooks:
    - webhook: <webhook name>
      connection: <connection name>
      filters:
        - path: action #Github event name
           value: opened
        - path: action #Github event name
           value: reopened
        - path: action #Github event name
           value: synchronize

```

Defining multiple webhooks with same name and connection, but different filters also doesn't work. We cannot use azure expressions to do it as well, because they cause pipeline syntax errors.

Having that information, I would say the easiest way is to use Prow/Tekton as coordinator and way to integrate Azure and GitHub
