### ISSUE TITLE
[CI] Integration of Tekton pipelines with hub and catalogs.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#7026]
**Description**

A tekton pipeline is an engine executing workloads on tekton k8s cluster. These workflows logic is defined in tasks and pipelines. A tekton pipeline will trigger a task or pipeline execution when notified by prow.

>Tekton Pipelines is a Kubernetes extension that installs and runs on your Kubernetes cluster. It defines a set of Kubernetes [Custom Resources](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/) that act as building blocks from which you can assemble CI/CD pipelines. Once installed, Tekton Pipelines becomes available via the Kubernetes CLI (kubectl) and via API calls, just like pods and other resources.

A tekton catalog is a repository which contains a Tasks and Pipelines definitions along with description. It can be implemented with github repository. It provides a versioned and defined structure and schema for storing and publishing Tekton resources.

>This repository contains a catalog of Task resources (and someday Pipelines and Resources), which are designed to be reusable in many pipelines.
>
>Each Task is provided in a separate directory along with a README.md and a Kubernetes manifest, so you can choose which Tasks to install on your cluster.

A tekton hub is GUI which give a developer a convenient way of search and sharing tasks and pipelines.

>The Tekton hub is a web based platform for developers to discover, share and contribute tasks and pipelines for Tekton.

It has following list of features:
  1. Display of resources in a curated way:
     User gets detailed information such as description, YAML, tags and rating of resources.
  2. Filter by  categories :
     This allows user to filter resources based on categories which will help user to get multiple resources.
  3. Search resources on the basis of `name` or `displayName`
  4. Rating
     - User can rate a resource based on the experience
     - This can even help the other user as by knowing the rating they can directly compare and use the resource
  5. Sort resources on the basis of name or rating.
  6. Install resources on cluster :
     - The Tekton Hub provides cluster installation commands for tasks or pipelines.

A tekton hub can collect resources from multiple catalogs. It's possible to combine a catalogs maintained by each Kyma team in their own repository together with public tekton catalog to reuse community developed tasks and pipelines. Similar like GitHub Actions provided by community.

An example ConfigMap wth list of catalogs to query.
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: tekton-hub-api
  labels:
    app: tekton-hub-api
data:
  CATALOG_REFRESH_INTERVAL: 30m ## change the catalog refresh interval here
  CATEGORIES: |
    - Automation
    - Build Tools
  CATALOGS: | ## Add the new catalog information here
    - name: tekton
      org: tektoncd
      type: community
      provider: github
      url: https://github.com/tektoncd/catalog
      revision: main
   - name: test-infra
      org: kyma-project
      type: community
      provider: github
      url: https://github.com/kyma-project/test-infra
      revision: main
   - name: btp-manager
      org: kyma-project
      type: community
      provider: github
      url: https://github.com/kyma-project/btp-manager
      revision: main
  SCOPES: | # Update the scopes as for your requirements
    - name: agent:create
      users: [vinamra28, piyush-garg, pratap0007, puneetpunamiya, sm43, sthaha, vdemeester]
    - name: catalog:refresh
      users: [vinamra28, piyush-garg, pratap0007, puneetpunamiya, sm43, sthaha, vdemeester]
    - name: config:refresh
      users: [vinamra28, piyush-garg, pratap0007, puneetpunamiya, sm43, sthaha, vdemeester]
  DEFAULT: | # This is default scopes required to rate a resource.
    scopes:
      - rating:read
      - rating:write
```

A resources collected from catalogs are presented in [hub](https://hub.tekton.dev/) web UI to let developers easily share and search available tasks.
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/12400578/220643354-39348b7f-649a-49db-a79a-53b9ce99321a.png">

It's possible to deploy own instance of tekton hub. Instruction is available in tekton hub github repository: https://github.com/tektoncd/hub/blob/main/docs/DEPLOYMENT.md

Tasks and pipelines presented in hub can be used in tekton pipeline through [built in remote Hub Resolver](https://tekton.dev/docs/pipelines/hub-resolver/). It allows developer to specify in PipelineRun or TaskRun a reference to Task or Pipeline definition by providing it's location in tekton hub.

```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: hub-demo
spec:
  pipelineRef:
    resolver: hub
    params:
    - name: catalog # optional
      value: tekton-catalog-pipelines 
    - name: type # optional
      value: artifact
    - name: kind
      value: pipeline
    - name: name
      value: buildpacks
    - name: version
      value: "0.1"
  # Note: the buildpacks pipeline requires parameters.
  # Resolution of the pipeline will succeed but the PipelineRun
  # overall will not succeed without those parameters.
```

As a second way of using Tasks and Pipelines, we can install all Tasks and Pipelines definitions existing in catalogs we query in a tekton pipeline k8s cluster. This installation can be simply automated with presubmit and postsubmit prowjobs. Where a presubmit prowjob can run some sanity checks and postsubmit would upload a k8s resource definitions to the tekton pipeline k8s cluster. This will be exactly the same process like updating a test-infra k8s resources on prow k8s cluster.

With such architecture:
- We allow each team to maintain their Tasks and Pipelines definitions in their repository without need to contribute to the one shared repository.
- We provide a developers with easy access to details of all Tasks and Pipelines available in our Tekton instance. A user can easily filter and search whole catalog in dedicated GUI console.
- We don't introduce additional mandatory rules and requirements for creating and using Tasks and Pipelines like namespacing or Cluster Tasks.
- We provide a complete catalog of all Tasks and Pipelines along with it's description and code.
- We enable developers to automatically share their definitions and easily reuse definitions of other teams.
- We provide our developers with access to Tasks and Pipelines developed by community.
