### ISSUE TITLE
Pjtester does not reflect right annotations

### ISSUE THREAD

**Issue by pPrecel** [kyma-project/test-infra#7088]
**Description**

When I use the pjtester to test the new building job I see that the `annotations` field is overriden ( [here](https://status.build.kyma-project.io/prowjob?prowjob=4a90f778-b756-11ed-a756-32e49bce8f1b) ). This field does not contain annotations implemented in [the PR](https://github.com/kyma-project/test-infra/pull/7028/files).

**Expected result**

we should have the following annotations:

```yaml
annotations:
  container.apparmor.security.beta.kubernetes.io/test: "unconfined"
  container.seccomp.security.alpha.kubernetes.io/test: "unconfined"
  pipeline.trigger: "pr-submit"
```

**Actual result**

we can see other annotations. AppArmor ones are missing:

```yaml
annotations:
  prow.k8s.io/context: anoipm_test_of_prowjob_pre-serverless-manager-operator-build
  prow.k8s.io/job: anoipm_test_of_prowjob_pre-serverless-manager-operator-build
```

**Comment by dekiel** [comment]
Annotations defined in tested prowjob definition are preserved now. [Test execution](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_serverless-manager/58/dekiel_test_of_prowjob_pre-serverless-manager-operator-build/1632878368376492032)

```yaml
annotations:
    container.apparmor.security.beta.kubernetes.io/test: unconfined
    container.seccomp.security.alpha.kubernetes.io/test: unconfined
    pipeline.trigger: pr-submit
    prow.k8s.io/context: dekiel_test_of_prowjob_pre-serverless-manager-operator-build
    prow.k8s.io/job: dekiel_test_of_prowjob_pre-serverless-manager-operator-build
```
