### ISSUE TITLE
Missing feature: Adding resource limits to container

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-project/test-infra#7549]
**Description**
Unfortunately, until now it is not possible to add resource limits to a prow pipeline if templates are used.

I used the following to set up a new pipeline: https://github.com/kyma-project/test-infra/blob/main/docs/prow/k3d-no-ssh.md
If templates are used to create a pipeline, then you can use `request_memory` and `request_cpu` to set the rquest size for the container. But this is not possible for the limit of memory and cpu.

Thus, the pipeline which require to have limits as stated in the example cannot be crated using templates.

**Expected result**
Introduce a mechanism to set limits to memory and CPU using templates.

**Actual result**
Not possible.

**Steps to reproduce**
Setup new pipeline, using templates. Set
```yaml
          resources:
            requests:
              memory: 3Gi
              cpu: 2
            limits:
              cpu: 1
              memory: 4Gi
```
in the template. Limits will not be rendered.

**Troubleshooting**
