### ISSUE TITLE
Insufficient resources on the PR clusters

### ISSUE THREAD

**Issue by Demonsthere** [kyma-project/test-infra#896]
**Description**

After the upgrade to istio 1.1 we have started seeing situations in which the clusters are going out or resources and are unable to install some required components. This is probably because of the amount of CPU requests connected to the number of istio side-car containers. 
In order to fix this, we need to upgrade the machines we are using to a higher tier, which would increase the costs fo those machines. 
Because of that we need firstly to move to xip to decrease the number of static IP and DNS costs as well as improve the quality of our cleaners to control the costs. 

**Attachments**

Status from the [logging deamonset](https://github.com/kyma-project/kyma/blob/master/resources/logging/templates/promtail/daemonset.yaml) on which this happened:
```
status:
  conditions:
  - lastProbeTime: 2019-04-16T06:35:23Z
    lastTransitionTime: 2019-04-16T06:25:43Z
    message: '0/4 nodes are available: 1 Insufficient cpu, 3 node(s) didn''t match
      node selector.'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  phase: Pending
  qosClass: Burstable
```
